### ISSUE TITLE
Question about NFS server

### ISSUE THREAD

**Issue by hans-permana** [wakonp/jupyterhub-deploy-swarm#1]
Hi @wakonp, I see that you are still updating the documentation, but I am too excited with your solution and tried it myself already :) I have some basic questions about it:
* How is it configured so that the NFS server container that is run at the main host can be seen and accessed by the other containers on the node host(s)? In the makefile I could not find anything that says this container should be run in a certain docker network. 
* Have you ever encountered a permission issue when mounting the nfs FS to the /exports inside the NFS server container? I have this situation that the FS that I want to mount has no no_root_squash attribute, so it makes it a bit tricky. I wonder if you have encountered such scenario.

**Comment by wakonp** [comment]
>How is it configured so that the NFS server container that is run at the main host can be seen and accessed by the other containers on the node host(s)?

I use the `nfs_start` function to run this docker command:
```
docker run -p 2049:2049 -v $(NFSSERVER_VOLUME):/exports -d --name jupyterhub_nfs --cap-add=SYS_ADMIN --env-file=.envNFS walki12/nfs-server jupyterhub jupyterUsers jupyterAssignments
```
There you can see that I forward the 2049 port of the NFS-Server Container to the main node. Other nodes, which are in the same network as the main node, can now access the NFS-Server Container via the IP of the main node. I  just use the Docker default network to start the container, because I do not specify any network.

>The bridge network represents the docker0 network present in all Docker installations. Unless you specify otherwise with the docker run --network=<NETWORK> option, the Docker daemon connects containers to this network by default. You can see this bridge as part of a host’s network stack by using the ifconfig command on the host.
https://docs.docker.com/engine/userguide/networking/#default-networks

In other words, you can run this container on any node in the network of the hosts and it **does not have to** be part of a docker swarm.


>Have you ever encountered a permission issue when mounting the nfs FS to the /exports inside the NFS server container?

Yes I have. If you want to use the NFS-Server with this repository unfortunately you have to set the `no_root_squash`. The reason for this problem is that I run/built the jupyterhub docker image as user `root`, so until now only the root user is able to spawn new services with the docker command. I will change this in the future (maybe this week) by creating a new user and adding him to a so called `docker` group, which should also have rights to execute docker commands. (The hub must be able to spawn notebookservers)

Coming back to the problem. Currently my jupyterhub image runs as root and is also using Docker NFS-Volumes. So the `no_root_squash` setting must be present, else the jupyterhub wont start because it can not access it's stored files on the NFS Server

**Comment by wakonp** [comment]
Hi @hans-permana ,
I just released v.0.2 of my repo. There juypterhub gets started with a non-root user. This will fix your `no_root_squash` problem.

**Comment by hans-permana** [comment]
> There you can see that I forward the 2049 port of the NFS-Server Container to the main node.

Thanks, I have tried this. Maybe it is worth mentioning that nfs-kernel-server has to be present on the host machine, otherwise it cannot be started inside the container? I also stated this issue [here](https://github.com/ErezHorev/dockerized_nfs_server/issues/6).

> There juypterhub gets started with a non-root user

Just saw the new `start.sh` of yours. Not sure if it will solve my issue, because the mounting is done on the notebook's container. I think the solution can be that a user with the same uid and gid as the one on the source NFS server is created on the notebook (and the NFS) container so that it can see the files. BTW, I ran all the docker operations as a non-root user that belongs to `docker` group.

**Comment by wakonp** [comment]
>Maybe it is worth mentioning that nfs-kernel-server has to be present on the host machine, otherwise it cannot be started inside the container?

Jeah I forgot to mention it in this repo but I think it is mentioned there:

>The nfs service of the docker container relies on the kernel of the native host to provide the kernel-level nfs support. If your nfs service is not up correctly, please make sure your native kernel does support nfs service.
https://github.com/ErezHorev/dockerized_nfs_server


>Not sure if it will solve my issue, because the mounting is done on the notebook's container.

OK. Which Authenticator do you use? I use the LDAPAuthenticator (obviously) and as mentioned my solution here:

>I did following:
>Before the username is returned by the Authenticator I call:
>
>docker exec -it NFS_CONTAINER useradd username
>docker exec -it NFS_CONTAINER mkdir /USERHOMESHARE/username && chown username >/USERHOMESHARE/username
>
>So the NFS_CONTAINER creates a new user for the authenticated username and provides a new >folder owned by the new user.
>
>One of the two mounts I mentioned in my previous comment points directly to the >USERHOMESHARE/username folder of my NFS_CONTAINER. So the user will always get his/her >shared NFS-Homefolder.
>
>Furthermore, before the notebook server is started via the arg in the container_spec, which is >start-singleuser.sh I call:
>
>NB_UID=docker exec jupyterhub_nfs id -u username
>NB_GID=docker exec jupyterhub_nfs id -g username
>
>This adds NB_UID and NB_GID to the ENV of the 'not yet spawned' notebook. Now the notebook >only needs to get started with the root user.
>
>The start.sh script checks if the Notebook-Server is spawned as root and takes the ENV variables >UID and GID and alters the $NB_USER (jovyan). At the end root starts the notebook as $NB_USER >which has the new NB_UID and NB_GID and can write in his/her NFS share.
>https://github.com/cassinyio/SwarmSpawner/pull/15

Foreach NotebookUser a NFS-User gets generated and the notebook server gets started with the UID/GID of the NFS-User. Therefore, the notebook server will write with the correct UID/GID on the NFS-Server.

>BTW, I ran all the docker operations as a non-root user that belongs to docker group.

That's how one should do it. In my setup I worked with the user root only because I work at my thesis only and I don't really care 😄.

**Comment by hans-permana** [comment]
> Jeah I forgot to mention it in this repo but I think it is mentioned there

Ah yes, it's there. I did not see it, thanks for pointing it out :)

> OK. Which Authenticator do you use? I use the LDAPAuthenticator (obviously) and as mentioned my solution here:

I think this is where our projects differ. I use GitHubAuthenticator and I can get away with creating just one common user for the shared user directory. Hence, the mounting happens only during the creation of the NB containers. In general the mounting works ok after modifying default user and UID/GID to the same one as in the NFS directory.  I can mount the shared directory into my NB containers, but because I don't have control on the NFS server, it is at the moment not possible to mount sub-dirs of this parent shared directory. 

I like your solution for differentiating permission for each individual user space, but I think to implement it for my project would require a bit more work to map GitHub IDs to a new local UID/GID, and also it does not add too many additional values at this point.

**Comment by wakonp** [comment]
>I like your solution for differentiating permission for each individual user space, but I think to implement it for my project would require a bit more work to map GitHub IDs to a new local UID/GID, and also it does not add too many additional values at this point.

Thanks, I now understand your use-case and hope all questions regarding this issue are solved. I will mention this in the wikis soon.
